<?php require "../components/head.php"?>
		<title>Getting Better at Bagpiping by Dealing with Mental Distractions</title>
		<?php $content = "I wanted to write down a couple of observations as of late and how it relates to the mind.  I’ve mentioned before in other blogs about the mind’s incessancy about chattering while we practice — and especially when we perform in front of others.";?>
		<meta name="description" content="<?php echo $content;?>">
		<link rel=“canonical” href=“https://www.nycbagpipes.com/bagpipe-blog/bagpiping-dealing-with-mental-distractions.php">
		<meta property="og:description" content="<?php echo $content;?>">
	</head>	
  <body>
		<?php require "../components/googleTagBody.php";?>
			<?php require "../components/learn-call.php";?>
			<?php require "../components/nav.php";?>
			
			<section class="blog-post-section">
				<div class="blog-post-div">
					<img class="blog-post-image" src="../img/yin-yang-bagpiping.jpg" alt="Yin and Yang Logo">
					<h1 class="section-title blog-post-title">Getting Better at Bagpiping by Dealing with Mental Distractions</h1>
					
					
					<p class="section-p blog-post-p">I wanted to write down a couple of observations as of late and how it relates to the mind.  I’ve mentioned before in other blogs about the mind’s incessancy about chattering while we practice — and especially when we perform in front of others.</p>
					<p class="section-p blog-post-p">This week I played a gig.  I was relatively happy with all of my performances but then I got to the last performance.  I was inside a bar room that had multiple TV’s on (the mother of all distractions). Then some woman started doing some weird hand gesturing to the beat of the music that was INCREDIBLY distracting.  My mind kept thinking about it.  Luckily I was playing the easy stuff.  I had marched back and forth while playing and had my mind return to the music, perhaps as a partial effort to get away from the hand gestures.  Then I went into the more difficult tunes, unfortunately I walked into an area of the room where I could see “the hand.”  “The hand” was invasive and pervaded my thoughts and I couldn’t concentrate…</p>
					<p class="section-p blog-post-p">Another time, while playing the same tricky tune, I was outside of a bar in Dumbo, Brooklyn.  While the atmosphere was festive; there was a group of people, who started clapping out of time with a weird rhythm (perhaps it was a cultural thing).  It started to throw me off so I had to distance myself away from them.  Perhaps I secretly hoped they got the message…</p>
					<p class="section-p blog-post-p">At a competition, while playing a section of my piobaireachd, a person walks by, raises their camera, and snaps a photo.  I played a wrong movement, which the judge noted in their scoresheet…</p>
					<p class="section-p blog-post-p">Earlier this week, I was practicing but my mind kept wandering about all the “news” on the pandemic.  In New York City, we have been experiencing massive COVID surges.  I myself thought I may have contracted the virus because I was feeling a little under the weather.  Furthermore the mood was weighing a bit heavily on me.  All this while trying to memorize one of my new strathspeys for competition season.  I’d start the tune off, my mind would wander on to the bad news, and then I made yet another memory mistake…</p>
					<p class="section-p blog-post-p">In Bruce Gandy’s <span class="italic">Delivering Your Own Awesome</span>, he writes one of the most comical lines in a book ever, where he describes that a competitor will announce their tune to a judge, nervously, embarking on the most terrifying 2 minutes of their life…  It begs the question: <span class="italic">why even bother to put oneself through such mental torture..?</span></p>
					<p class="section-p blog-post-p">The truth is a lot of piping is mental.  In fact, a lot of life is mental.  We are often in our heads.</p>
					<p class="section-p blog-post-p">When we pipe, we might be thinking about: <span class="italic">fixing the doubles, holding more of these notes and cutting the others, what are the next notes of this bar, is my bag losing air, should I turn yet, why is the pipe major giving me the evil eye, the bandmate next to me who stinks at playing, whether I’ll make the band.  </span>Then there are other endless distractions outside of piping: <span class="italic">who is calling me, did I pay my bills, what time is my appointment, I’m thirsty…</span>  All this, while we’re "supposed to not think about anything" and make the whole thing look effortlessly…so we can just quite simply let ‘er rip.</p>
					<p class="section-p blog-post-p">The truth is there is a duality that exists, at least in piping.  There is a part that requires thinking, but there is also a part that is creative and expressive, that seeks to liberate from the clutches of the thinking part of the brain (which is perhaps the point of art).  Don’t get me wrong, the thinking part does have its place.  It can make you question whether you’re playing a tune or an embellishment correctly.  After all, practicing without any sort of critical thinking isn’t very useful because you won’t be able to address any of your problems.  However worrying about your doublings isn’t going to help you much during a live performance; in fact it will probably make it worse.  Is there a way to turn off the brain when you need to?</p>
					<p class="section-p blog-post-p">I decided to see if I can turn my thoughts off with some meditation.</p>
					<p class="section-p blog-post-p">Meditation is a practice of acknowledging ones thoughts as merely just what they are.  Rather than paying too much attention we can choose to pay less attention to random thoughts, and be able to focus our mind on what it is we are doing: whether it is performing or practicing.  </p>
					<p class="section-p blog-post-p">So how do we do this?  For one, I am a big fan of turning off all electronic devices when practicing, that means putting the phone on airplane mode, wifi off.  This at least eliminates some of the external distractions.  Set a timer.  This way it forces you to commit.  Make it a small amount of time.  5 minutes.  To be honest I kind of hate meditating; I suspect a lot of people feel the same way; it’s like “having to go” to the gym (but usually you’re happy afterwards).  That’s why I make the time small to begin with.  While meditating try not to think about anything.  It’s ok if you do, since it’s not going to happen automaticly.  It’s like going into the woods.  You gotta just take it in.  Once you start to let yourself go a bit it’ll get easier.  When the timer goes off, choose if you want to continue or not. While the purpose of this article is not to go into how to meditate (because after all, we’d rather bagpipe, right?), there are countless resources on how to meditate if you want to explore that.  But it is good to be aware of what role your mind plays in the bagpiping process, amongst everything else (as you try to liberate yourself from being hyper-aware, of course).</p>
					<p class="section-p blog-post-p">Another good trick is to find a time during your practice or a day of the week, where you automatically record yourself as if you were performing live.  Like the Eminem song says, “You only get one shot.”  But using the random “one-shot” recording method, it forces you to go into that mode.  It also allows you to honestly assess yourself on how you “performed.”  And it’s OK if you mess up; that is quite simply feedback that you need to do homework.</p>
					<p class="section-p blog-post-p">As for “the hand” and other external distractions, that can be difficult to deal with.  I was once watching the Metrocup Bagpipe competition, which is one of the biggest solo bagpiper competitions in North America.  While I was returning from the bathroom, a performance was about to begin.  I was not allowed back into the performance room until after the performance was over to prevent distracting the person who was preparing to go on.  Unfortunately, we all don’t have that luxury when we perform.  We have to find a way to deal with external distractions.  That’s part of what being a good performer entails.  One thing might be to get away from the distraction as much as possible: go to the opposite side of the room, close your eyes, turn away.  If you are in an environment with a lot of distractions, maybe play simpler tunes.  And if you still mess up, that’s OK too.  Nobody is perfect.   Seeking perfection sometimes causes more imperfection as well; this is actually a topic that Victor Wooten’s <span class="italic">The Music Lesson</span> deals with.  While I only read 2 random pages from the book, I can tell that the book deals well with some of the topics discussed in this article.  Although I haven’t read the book yet, I’ve met many good bagpipers raving about the book.  I plan on writing an article on it when I’m down; I was already impressed with the 2 pages that I randomly read.</p>
					<p class="section-p blog-post-p">In short, “let it go.”  It’s not easy to do; and yet it is.</p>
					
          <p class="section-p blog-post-p section-border-space"><span class="italic">Published: January 1st, 2022</span></p>

					<p class="section-border-space"></p>
					<div class="section-border"></div>
					<p class="section-p questions">Have any questions? Shoot me an <a href="mailto: nycbagpipes@gmail.com">email</a>.</p>
					
				</div>
			</section>
		
			<?php require "../components/footer.php";?>
		<script src="../script.js"></script>
	</body>
</html>