<?php require "../components/head.php"?>
		<title>How to Memorize Bagpipe Tunes Faster</title>
		<?php $content = "Part of what I think about in my quest to get better as a bagpiper is to how to learn tunes faster and how to teach this to others. I’ve been thinking about how we learn and what is effective.  I’ve learned and talked to people about their memorization methods and read books on it.  Some of it I found helpful; some of it not so much.";?>
		<meta name="description" content="<?php echo $content;?>">
		<meta property="og:description" content="<?php echo $content;?>">
	</head>	
	<body>
		<?php require "../components/googleTagBody.php";?>
			<?php require "../components/learn-call.php";?>
			<?php require "../components/nav.php";?>
			
			<section class="blog-post-section">
				<div class="blog-post-div">
					<img class="blog-post-image" src="../img/brain-running-faster.png" alt="Cartoon of Brain Running Faster">
					<h1 class="section-title blog-post-title">How to Memorize Bagpipe Tunes Faster</h1>
						
					<p class="section-p blog-post-p">Part of what I think about in my quest to get better as a bagpiper is to how to learn tunes faster and how to teach this to students. I’ve been thinking about how to memorize and what is effective.  I’ve learned and talked to people about their memorization methods and read books on it.  Some of it I found helpful; some of it not so much.  </p>
					<p class="section-p blog-post-p">One of the things that I had learned (the hard way) is not to learn a tune “linearly”.  In other words do not try to memorize everything from A-Z.</p>
					<p class="section-p blog-post-p">Think about it. Remember when you were learning a new language in school?  What did you start with?  Just words and phrases.  Nobody in their right mind is expected to have a fluent conversation or memorize paragraphs.</p>
					<p class="section-p blog-post-p">We also have phrases in bagpipe music.  The phrases are components of the tunes, giving meaning and structure to a tune.  Know that part of a tune you love?  Usually there’s an exciting phrase that sticks out.  And by breaking down the tune into phrases the tune is easier to learn. (You might even want to jump straight to your favorite section of a new tune).</p>
					<p class="section-p blog-post-p">In case you are wondering what a phrase is, it’s like a sentence, going back to the language allegory.</p>
					<p class="section-p blog-post-p"><span class="italic">Happy Birthday to You</span> is an example of a musical phrase from one of the most famous songs ever.</p>
					<p class="section-p blog-post-p">The next phrase repeats: <span class="italic">Happy Birthday to You…</span></p>
					<p class="section-p blog-post-p"><span class="italic">Happy Birthday Dear Cristopher…</span>  another phrase…</p>
					<p class="section-p blog-post-p"><span class="italic">Happy Birthday to You…</span> and the final phrase concludes.</p>
					<p class="section-p blog-post-p">You get the message.  Break down the tune into phrases. After you develop confidence in memorizing one phrase move to the next.  Usually I try to play it a few times without making a mistake, before moving on.  After you memorize the next phrase, join it with the previous phrase you memorized to make sure everything works and to reinforce your memory.  Then keep memorizing more phrases, join them together, and keep building.</p>
					<p class="section-p blog-post-p">In case a phrase is either too difficult to play or memorize, break that phrase down into even smaller parts, perhaps into just a bar or even less.  Keep breaking it down and memorize the smaller parts of the phrase until you’re ready to move on.</p>
					<p class="section-p blog-post-p">The latest thing that I’ve been incorporating is using auditory feedback to learn the tunes better and faster.  This has so many advantages.  This assumes that you have a recording of a high quality performance of the tune you wish to learn.  I find this helpful for so many reasons right now.   And listening to a recording will help you get away from the sheet music FASTER.</p>
					<p class="section-p blog-post-p">Now that the fall is here I’ve taken up the challenge of learning a bunch of new tunes before we start competing again in 2022. Currently I’m working on an entire new repertoire of music for the St. Columcille Grade 3 band from Kearney, NJ.  That band is no joke.  Not only do I have an entirely new MSR and medley of tunes to learn, but these tunes require a high degree of accuracy in rhythm, expression, and technique to meet the band’s standards. I don’t say this lightly, because the more I think about this the more I realize notation sucks. It really only conveys a percentage of the tune that needs to come out in our performance of the tune, which is why I’m going to get into the usefulness of auditory feedback.</p>
					<p class="section-p blog-post-p">In fact, this is something that I’ve learned to incorporate with new students.  I used to jump into teaching the basics of the practice chanter, such as playing different notes and rhythms WHILE having them do sight reading, which was very difficult.  Usually it is too much coordination at once for the student. Nowadays I try to just focus on the auditory aspect of learning music.  Rather than have students read the music in order to play the notes, now I just sing phrases to them while introducing the notes.  They learn so much faster and intuitively this way since they get to hear the melody (and my beautiful voice)!</p>
					<p class="section-p blog-post-p">Music in essence is strongly related to spoken language as mentioned before.  So much of bagpiping revolves around the rhythms and micro rhythms (found in the embellishments), which very closely resemble vocal syllables.  After all, piobaireachd (the ancient music of bagpiping) was always transmitted to the student orally and had a full language of vocable symbols; this language was called canntaireachd (which means chanting).  Therefore, it only makes sense to reinforce the expression of music by at least hearing something rather than just reading it.  <a href="https://www.youtube.com/watch?v=39cLgPCRDDA&feature=youtu.be" target="_blank">You might find this video interesting showing the relationship between bagpiping and language.</a></p>
					<p class="section-p blog-post-p">So now that I’m learning a ton of new music for next season, a lot of times I find myself trying to remember the melody and the phrases mentioned before.  This becomes especially tricky when we don’t have the melody in our heads yet.  At least if you know the melody of a tune in your head, you will have some direction.  I’ve always found that a tune is much easier to learn when that is the case. Even if you are unsure of the notes of a phrase, sometimes you can kind of guess the notes.  You even have an understanding of how the rhythm is supposed to be.</p>
					<p class="section-p blog-post-p">So...what if the tune is unknown or we don’t know it very well?  Well, I’ve recently started using the wonderful <a href="https://anytune.us/"><span class="italic bold">Anytune</span></a> app for that.  Although the intention of that app may be more for getting really good unison or perhaps even learning a tune by ear, my latest craze is incorporating <a href="https://anytune.us/"><span class="italic bold">Anytune</a></span> with my practice and memorization of melodies that I don’t have in my head yet.  Listening back to the tune on repeat gives us the auditory feedback that WE NEED in order to memorize faster and play better.  The app has a looping feature that easily allows you to focus on certain sections, ESPECIALLY for those lines, phrases, bars, or whatever section we choose to focus on. This allows us to then hear and memorize the tune, including the subtleties of the expression, rhythm, and techniques that are fundamental to performing the tune better.  This compounds and makes the entire process SO MUCH FASTER!  As you play alongside with it, it will even help you develop your fingers AND your ears for unison, with the recording.  And getting better at unison is critical for development when playing with any serious band.</p>
					<p class="section-p blog-post-p">I have one last last useful thing to share, going back to using sheet music. When looking at sheet music it is <span class="bold">crucial</span> the degree of focus we have while memorizing the notes on the sheet.  By doing so, we have a better chance of memorizing it.  That cannot be understated since focusing really does make a big difference but can be easy to overlook, especially with so many daily distractions.  Cell phones are notorious for distractions, so sometimes I’ll put it away.  If I’m using the cell phone's metronome I at least usually mute the phone and put it upside down (so not to see text messages or app notifications).  Don’t ignore the dangers of the cell phone, but if it is used responsibly it can actually help, such as the usage of <span class="italic">Anytune</span>.  Again make sure to concentrate even when looking at the darn sheet music!</p>
					<p class="section-p blog-post-p">I hope this article helps you learn faster!  Happy piping!</p>
          <p class="section-p blog-post-p section-border-space"><span class="italic">Published: October 15th, 2021</span></p>
					
					<div class="section-border"></div>
					<p class="section-p questions">Have any questions? Shoot me an <a href="mailto: nycbagpipes@gmail.com">email</a>.</p>
					
			</section>
		
			<?php require "../components/footer.php";?>
		</div>
		<script src="../script.js"></script>
	</body>
</html>