<?php require "../components/head.php"?>
		<title>Playing Your First Bagpipe Solo Competition</title>
		<?php $content = "I remember my first time competing.  I was playing the piobaireachd (ground only) event and I was so nervous that I couldn’t remember if I had repeated this first part.  I guess it didn’t go too badly because I got 2nd place.  Not bad considering that I thought I may have botched the performance.  I was so nervous!  Heart pounding; couldn’t think; fingers were shaking so much I was surprised that I could even play anything remotely related to music.  Little did I know this would become the first of many other contests and events, where on a spur I would drive hundreds of miles to get to other ones.";?>
		<meta name="description" content="<?php echo $content;?>">
		<meta property="og:description" content="<?php echo $content;?>">
	</head>	
	<body>
		<?php require "../components/googleTagBody.php";?>
			<?php require "../components/learn-call.php";?>
			<?php require "../components/nav.php";?>
			
			<section class="blog-post-section">
				<div class="blog-post-div">
					<img class="blog-post-image" src="../img/playing-your-first-bagpipe-solo-competition.jpg" alt="Trash Dumpster on Fire">
					<h1 class="section-title blog-post-title">Playing Your First Bagpipe Solo Competition</h1>
											
					<p class="section-p blog-post-p">I remember my first time competing.  I was playing the piobaireachd (ground only) event and I was so nervous that I couldn’t remember if I had repeated the first part.  I guess it didn’t go too badly because I got 2nd place.  Not bad considering that I thought I may have botched the performance.  I was so nervous!  Heart pounding; couldn’t think; fingers were shaking so much I was surprised that I could even play anything remotely related to music.  Little did I know this would become the first of many other contests and events, where on a spur I would drive hundreds of miles to get to other ones.</p>
					<p class="section-p blog-post-p">The first contest itself also was a spur.  My friend told me that there was a competition coming up in Long Island.  It was at the Irish AOH Feis, which was notorious for having 100’s of Irish step dancer girls tapping in every nook and cranny.  Ironically my friend couldn’t go because of a wedding.  When I checked the deadline had passed, but the contest organizer allowed me to still enroll thankfully.</p>
					<p class="section-p blog-post-p">The second event was the 2/4 march.  I saw Mike Faughnan around (from Saffron and Metro Pipe Band) and he gave me a hand tuning my chanter.  He told me to take it easy because I was over-blowing.  I thought I was playing normally.  Those nerves...</p>
					<p class="section-p blog-post-p">I went into playing <span class="italic">John MacDonald’s Welcome to South Uist.</span>  I’m sure I was equally as nervous as before.  It was hard to march but I moved.  After I was done I got congratulated by some happy competitors. Always reassuring.  I got 3rd out of 11.  Not bad for a first contest…  Actually that’s pretty good…</p>
					<p class="section-p blog-post-p">A lot has changed since that day.  I had met someone at the competition who had told me about this band that cared a lot about playing well, which I shortly joined after. I upgraded my pipe setup (got a sheepskin Begg).  I had started to take lessons regularly with an instructor.  I started to learn about the different idioms.  I worked on fixing my technique.  I learned some history of bagpiping.  After over 20 years of playing on and off not very seriously, I started to really begin a proper journey, giving due respect to this grand instrument.</p>
					<p class="section-p blog-post-p">I really owe a lot to bagpipe competing (including band competitions).  It has changed me for the better and motivated me to get better as a player.  I have spent countless hours trying to improve particular tunes for the season.  After getting upgraded to Grade 3, I was thrown into heats where I started to get my butt kicked.  Thankfully I had a friend who was very interested in competing so we travelled together to a lot of the contests.  I didn’t do too hot in the beginning of the new grade but I was determined to get better.  At my peak I was most certainly playing every day, especially my piobaireachd <span class="italic">Lament for the Old Sword</span>, which is a technically challenging tune for Grade 3 (at least in my opinion) <a href="https://www.youtube.com/watch?v=WLJ-mFrNNA0">because it has a crunluath a mach variation.</a>  That all paid off when at Loon Mountain I received my first AGL and 2 first places.  Had it not been for a break down in my 2/4 march, I think I might have clinched piper of the day.  But it was still a good run.  The diligence paid off.</p>
					<p class="section-p blog-post-p">I still am practicing a lot for my competitions.  As I write this article in the fall of 2021, I am learning a lot of new music for my band.  I decided to try out for the highest grade band that my band offers while remaining committed to my goal of becoming a Grade 1 solo bagpiper.  Many people would not go this route but I think with good time management and patience I may get lucky in at least one of those areas.</p>
					<p class="section-p blog-post-p">So you have been thinking about competing?  The first thing I would say is just to do it.  Just like there’s no need to prolong going into cold water, it’s easier if you just get it over with.  Unfortunately I think a lot of bands do not encourage their players to compete in solo competitions, aka "to solo" or "solo bagpipe."  I was told that <a href="https://www.pipesdrums.com/article/George-M-Bell-1926-2010-updated/">Pipe Major George Bell</a> back in the day used to encourage all the members of his band "to play solos", and I think that’s a great thing on so many levels.  If the individual piper improves, so does the band.</p>
					<p class="section-p blog-post-p">A lot of people have a fear of playing by themselves as a piper.  I never used to really get nervous when I was young and had first learned.  The nerves started to definitely creepy in as I got older.  But this is sort of the courage it takes to get in front of a judge.   Their job is, after all, to judge you, so if you mess up they may indicate that.  They really do want you to do well though, and most of the judges I’ve met seem to really care about continuing the highland arts and culture.</p>
					<p class="section-p blog-post-p">A lot of this fear just exists in the mind anyway.  And it really does become a game of how to manage your thoughts.  Of course, since fear does have an effect physiologically on the body, it will interfere with your playing.  But think more about the long haul and what you seek to get out it.</p>
					<p class="section-p blog-post-p">The person who I travelled with to a lot of my competitions has terrible performance anxiety.  She could have simply decided not to go on, or maybe just quit early.  However she decided to face her fears.  She ended up getting 1st place overall that season.  So good for her.  And it shows the power of dealing with the uncomfortable.</p>
					<p class="section-p blog-post-p">And I think that says a lot, because we are so exposed in our culture to avoid discomfort, with endless distractions.  But if you choose the more difficult path of facing your fear of playing (assuming you have one), it will make you a better person.</p>
					<p class="section-p blog-post-p">Another reason why it’s great to solo compete is that it will make you address your deficiencies in bagpiping.  Is there a part in the tune where you are struggling?  Address it.  Are you not great at tuning drones?  Address it.  Are your pipes falling apart?  Address it.   The deadline of having a competition will motivate you to get better.</p>
					<p class="section-p blog-post-p">Now you don’t have to overwhelm yourself with addressing everything at once.  Certain things may take a long time to address.  When I first entered grade 3, the judges kept complaining about my crossing noises.  It’s all I heard.  And... I kept trying to fix it, but the problems were so engrained in my playing from 20 plus years that the bad habits needed to be SLOWLY unbroken.  And that isn’t easy.  This is why it’s important to be patient.  Eventually I managed to address the problem, with the occasional crossing noises still creeping in (but it has improved a lot).  The point is: it’s more of a process rather than a checklist.</p>
					<p class="section-p blog-post-p">Not to say that you shouldn’t set goals.  Obviously if we go to a competition, many of us want to do well, or, at least, not poorly.  But even doing poorly has its place, as I’ve done many times before.  There’s a saying in chess (which I also play a lot of) that you learn more from a loss than a win.</p>
					<p class="section-p blog-post-p">Well, even though this article was intended to be a guideline, I sort of veered off to reminisce about my experience. I do, however, want to share a few suggestions...</p>
					<h2 class="section-title blog-post-title">Here are Some Tips for Playing Your First Bagpipe Competition:</h2>
          <ol class="blog-list">
            <li class="blog-list-item"><span class="light-bold">Commit to starting.  </span>As I said before…  <span class="italic">just do it.</span>  You will need to enroll with a local association, e.g., the <a href="http://euspba.org/">EUSPBA</a> (which covers eastern United States) or <a href="https://rspba.org/">RSPBA</a> (which covers the U.K.), or wherever is near you.  You will also need to find competitions within that association and enroll.  Just google for some.  The main part of the season is from Spring to Summer.  In the Fall and Winter is a good time to prepare!  But don't let that dissuade from <span class="italic">just doing it!</span></li>
            <li class="blog-list-item"><span class="light-bold">Practice.</span>  Although you cannot get rid of your nerves.  Practicing a lot will make it much more likely that the performance goes well.  Practice will also make you address issues that you didn’t address before.</li>
            <li class="blog-list-item"><span class="light-bold">Practice more.</span>  I’m not saying you need to practice all the time, but it should be more than what you were doing before you signed up for the competition.</li>
            <li class="blog-list-item"><span class="light-bold">Consider taking lessons.</span>  A qualified instructor will help you address your weaknesses and give you suggestions.  They are like a coach and life partner.  Use the time with them effectively (some love to chat).  For piobaireachd they will offer necessary guidance.   A good instructor knows what to address.  I’ve heard of suave instructors who will address your issues in order of importance so that you do better in competitions.  Other instructors take the slow and steady approach.  You may not do great initially but you will become a stronger piper in the long run.  Either way a qualified instructor is very beneficial.</li>
            <li class="blog-list-item"><span class="light-bold">Find a buddy to go to competitions with.</span>  I think this helps a lot.  It will motivate you more since you have a partner.  You could even meet up and perform in front of each other as a practice run.  If the competitions are far you will have someone to keep you company, motivate you to go to more competitions, and split a hotel room with.</li>
            <li class="blog-list-item"><span class="light-bold">Pick tunes that aren’t too difficult.</span>  I actually had a Glenfiddich competition champion tell me that the tunes that I was playing were too difficult for my grade.  As Jack Lee says here, <a href="https://www.youtube.com/watch?v=q0WwTMPeSTI&feature=youtu.be">you don’t get points for playing difficult tunes.</a>  (You lose them when you mess them up).  There is no need to make it more difficult, especially since you’ll be under pressure.</li>
            <li class="blog-list-item"><span class="light-bold">Make sure your pipes are in good order (ahead of time).</span>   Your chanter should be in tune, drone reeds should be in good shape.  Joints are sealed well.  Tuning pins are not too loose or tight.  You want to make sure everything is in pretty good shape at least by a few days before the competition so there are no issues.  It helps to have backup reeds and drone reeds in case something goes wrong.  I once had my bass drone reed die about a minute before my 2/4 march. Thankfully I had my band drone reeds on me.  I got an AGL for that competition but it could have gone sour had I not had the bass drone reed backup.  Lastly, you don’t want to go crazy the night before making any big changes.  Before my Loon Mountain competition where I had a break down, I got too cavalier with keeping the bass drone reed calibrated weakly a few days before the competition.  After a long day competing with 5 events, the moisture came in, and I probably got excited and over-blew a note (remember those nerves?) - the bass drone shut off.  That cost me.  My rule is don’t go crazy with adjustments too close to the event.</li>
            <li class="blog-list-item"><span class="light-bold">Stay focused.</span>  One of the things that Bruce Gandy talked about in his new book <a target="_blank" href="https://www.amazon.com/gp/product/B08GQGLNHN/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B08GQGLNHN&linkCode=as2&tag=nycbagpipes-20&linkId=65b41bf793a4f541c295faf6c7d15b55">Performance: Delivering Your Own Awesome</a> is imagining what it will be like when you are performing.  Set a timer.  After warming up, when your timer goes off play as if you were playing in front of the judge.  This will prepare your mind to go into a "I am ready” mode.  As you're playing, stay focused on the music.  It’s not easy.  The brain is notorious for keeping itself distracted from tedious things.  So as you are playing you might start thinking about your holiday plans… or that you’re hungry… or that you have to pay the bills… or that you messed up a note…  When that happens gently dismiss the thought and return to focusing on playing.  You cannot completely eradicate the brain’s chatter, but you can constantly remind yourself to focus.  And you will get better at it-the more you practice-and focus-on it.  That is part of the process.</li>
            <li class="blog-list-item"><span class="light-bold">Do not drink alcohol.</span>  I remember I was at a games once and this guy was so nervous he was slamming down pints.  Not only does that look bad, but it puts a band aid on the problem.  Perhaps your nerves will slightly be dulled but so will your playing and technique.</li>
            <li class="blog-list-item"><span class="light-bold">Get a good night rest.</span>  Especially as older adults, we require adequate sleep so that our mind is relaxed and not cranky.  This means not partying the night before (avoiding drinking too much).  This may seem obvious, but when staying at a hotel — or with your band — the night before, sometimes the tendency is to let loose.  Try to get some high quality sleep.  I am a fan of using a sleeping mask, especially in a hotel.</li>
            <li class="blog-list-item"><span class="light-bold">Exercise regularly to keep the mind sharp.</span>  <a href="https://www.youtube.com/watch?v=rJtTrJusvVk">See how Bobby Fischer prepared for chess by also doing exercise.</a>  It’s serious.  One of my favorite things to do the morning of the competition is to go for a run, especially if I’m staying at a hotel with a gym.</li>
            <li class="blog-list-item"><span class="light-bold">Stretch your fingers!	</span>  One of my favorite tricks, especially for older players who don’t have the same dexterity as the teenage players.  I find this makes my fingers move so much better!  (Imagine if we did this every time before and after we practiced)!</li>
            <li class="blog-list-item"><span class="light-bold">Get to the competition early.</span>  You’ll need time to check in.  The organizers will give you a number (your competition number) which you pin to your kilt.  It’s not a bad idea to bring a baby pin, but often organizers will provide that.  Usually competition organizers will email you the times of your events a few days in advance, but these are somewhat loose.  It’s usually good to get to the competition about an hour before your first event so that you have time to warm your pipes up.  In case you don’t know, bagpipes take  time to warm up and be in tune, so you don’t want to show up 5 minutes before your competition with untuned bagpipes and nervous because you were late.</li>
            <li class="blog-list-item"><span class="light-bold">See the steward.</span>  The steward is like an assistant for the judge who helps assist with things moving along.  When you see them, just let them know you are there (that you actually arrived to the games).  If you don’t have to play for a while then you can go about your business and prepare.  If you are going up shortly it’s good to stay near, but remember to keep your pipes in tune (playing it once in a while) so they don’t get cold.</li>
            <li class="blog-list-item"><span class="light-bold">Warm up (but don't overdo it).</span>  It’s good to get the fingers moving.  Obviously don’t tire your fingers out though with too much playing. I also prefer to play on an electronic chanter if possible so I don’t tire my lips out, especially before a piobaireachd.  That being said, you’ll want to play the pipes a bit to keep them warmed up, but don’t overdo it so that when you perform you are tired.  Playing tired, usually yields bad results.  Also, I usually avoid playing competition material when warming up.  This is because the brain gets bored doing repetitive activity and that can come out in your playing and expression of the tune. I might just play a tune only once before.</li>
            <li class="blog-list-item"><span class="light-bold">Shut off your phone.</span>  It's an unnecessary distraction.  You need to be FOCUSED!</li>
            <li class="blog-list-item"><span class="light-bold">Play a tune while the competitor before you is performing.</span>  Again, this is to warm your pipes up so that when you see the judge the pipes are (near) ready.</li>
            <li class="blog-list-item"><span class="light-bold">Wear ear plugs.</span>  This is a cool trick that someone taught me. Aside from the benefit of protecting your hearing, ear plugs help you tune out other bagpipes.  (Sometimes there’s dozens going on).  This will make tuning your drones to the chanter a lot easier.  This is critical when you are in front of the judge but difficult when there is pressure to do it well with so many other bagpipers around in the background playing.  The plugs help to block some of that noise out.</li>
            <li class="blog-list-item"><span class="light-bold">In front of the judge...</span>  Greet them.  Be confident (or try to be).  Be polite.  They will ask you for what tune you will play.  You may want to write it down (helpful when you have many tunes to play; this is so easy to overlook).  Again give a quick tuning of your bagpipes.  If they sounded good don’t go too crazy making them perfect.  Lastly, there is a sort of an art to starting a tune.  Usually I like to hold the E to indicate to the judge you are about to start (rather than randomly starting).  This will make you look smarter (you definitely want to give a good impression) on your start.  If it’s a marching tune, I will start to march to get the tempo into my head.  Sing the tune in your head.  It’s all about the preparation and getting you ready.  And when you’re ready, <span class="italic">let ‘er rip.</span></li>
            <li class="blog-list-item"><span class="light-bold">STAY FOCUSED!</span>  Any negative thoughts in your head, just dismiss them and stay focused on the music as much as possible.  Someone is taking your photo (oh yes, that happens), stay focused.  Is there a garbage can on fire in the yonder distance?  (Yes, this happened to my friend).  Stay focused.  The trees look beautiful?  Stay focused.  Some guy is drunk and wants to pick a fight with you during your piobaireachd.  (This also actually happened to my other friend).  Stay focused!  STAY FOCUSED!</li>
            <li class="blog-list-item"><span class="light-bold">Go over the score sheets.</span>  After the event for everyone is over, you will have access to your score sheets.  The score sheets ought to show the professional advice from the judge on what they liked and disliked in your performance and how to improve.   Some judges are articulate; others not so much.  But I did hear a judge/performer once comment not to dismiss even basic comments from the judge.  It’s good to try to even make sense of the comments that don’t seem meaningful so you don’t put it off.  Putting off comments has a tendency to make those same comments repeat later. So the sooner you address your issues, the sooner those comments go away.  It's also very helpful to show the sheets to your instructor.</li>
            <li class="blog-list-item"><span class="light-bold">Do it again!</span>  You may wonder why you ever signed up in the first place for this.  But once it’s over people often feel elated.  There’s a sense of great satisfaction of taking up the challenge of competing in this dopamine-driven, electronic-distractive world.  It’s a higher type of reward.  It can give ups and downs, but there’s nothing quite like it.  Even if you don't feel elated, or perhaps even feel down, there's still a lot to learn and benefit from competing in solos.  I hope that you will enjoy it and keep at it!</li>
				  </ol>
					<p class="section-p blog-post-p"></p>

          <p class="section-p blog-post-p section-border-space"><span class="italic">Published: October 22nd, 2021</span></p>
					
					<div class="section-border"></div>
					<p class="section-p questions">Have any questions? Shoot me an <a href="mailto: nycbagpipes@gmail.com">email</a>.</p>
					
			</section>
							
			<?php require "../components/footer.php";?>
		</div>
		<script src="../script.js"></script>
	</body>
</html>