<?php require "../components/head.php"?>
		<title>Ross Vs. Faegerstrom Vs. Blair Electronic Bagpipe Review</title>
		<?php $content = "In this article I cover my opinions on some of the electronic bagpipes on the market.  Part of my opinions are based upon my experience as an electronic musician where I had programmed and even repaired many synthesizers—aside from bagpiping.";?>
		<meta name="description" content="<?php echo $content;?>">
		<meta property="og:description" content="<?php echo $content;?>">
	</head>	
	<body>
		<?php require "../components/googleTagBody.php";?>
			<?php require "../components/learn-call.php";?>
			<?php require "../components/nav.php";?>
			
			<section class="blog-post-section">
				<div class="blog-post-div">
					<img class="blog-post-image" src="../img/cadillac.jpeg" alt="Cadillac Logo on Steering Wheel">
					<h1 class="section-title blog-post-title">Ross Vs. Faegerstrom Vs. Blair Electronic Bagpipe Review</h1>
        
					<p class="section-p blog-post-p">In this article I cover my opinions on some of the electronic bagpipes on the market.  Part of my opinions are based upon my experience as an <a targer="blank" href="https://www.youtube.com/watch?v=0F6Q9bOr5bM">electronic musician</a> where I had programmed and even repaired many synthesizers—aside from bagpiping.</p>
					<p class="section-p blog-post-p">My first electronic bagpipe was the Ross electronic bagpipe which I had purchased back in 2015.  Actually the first time I ever played one was back in 1997; this was when I was first learning on a practice chanter.  It was a rather mystical looking thing.  <span class="italic">Electricity plus bagpipes?!</span>  And this was back in 1997: before the interwebs, when the bagpipe world was still very small and extremely disconnected.  There were no pipe websites, blogs, and online stores.  Outside of your pipeband there was a good chance you had no connection to piping beyond that immediate circle.  So the technology, of this “big box”, was quite interesting.  It was quite a cool thing—for the time.</p>
					<p class="section-p blog-post-p">So when I had bought this thing in 2015 obviously a lot of time had elapsed.  Back then I was beginning to take piping more seriously.  After I had purchased it, I found myself using it a lot.  There were a lot of useful features: volume control as well as a headphone jack, which I think is great when you are living with other people.  I’ve always found practicing like going to the bathroom or parking a car; it tends to go better when nobody is looking.  So with that, the Ross chanter had me playing a lot more.</p>
					<img class="blog-post-image" src="../img/ross-elctronic-bagpipe-older.jpeg" alt="Ross Electronic Bagpipe Older Model">
					<p class="section-p blog-post-p">It should be mentioned that my experience with the Ross is with one of the older models like shown above.</p>
					<p class="section-p blog-post-p">Then…eventually…it stopped working properly.  The “F” note sensor started to trigger constantly to the point where it became unbearable to play.  I tossed it aside.</p>
					<p class="section-p blog-post-p">The Ross doesn’t have a whole lot of other features except that you can shut the drones off (wow) and change the key of the instrument (ok).  I was not a big fan of the sensors, particularly when they didn’t sense my fingers.  The “fix” for that, according to the manual, is to use soap and wash your hands your hands because they are dry.  But really?  Do I need to carry around soap to practice?  And even using soap I found only somewhat lessened the problem at times.</p>
					<p class="section-p blog-post-p">In 2018 I really started to get serious about piping so I bought the Faegerstrom TechnoPipes.  As of this article there’s 3 versions of Faegerstrom products; the TechnoPipes version has extra features (metronome, extra instruments) over the original TechnoChanter.  However their newest product is called the TechnoChanter 2nd gen. and has many of the TechnoPipes’ features.</p>
					<img class="blog-post-image" src="../img/kraftwerk.jpeg" alt="Kraftwerk Band Photo">
					<p class="section-p blog-post-p">Aside from their products sounding like the names of Kraftwerk albums, some of the things I love about the Faegerstrom is that it’s extremely light and portable.  It’s pretty sleek too so you could get away with putting it in your pocket (if you don’t mind a bit of a bulge).  In fact, it’s so sleek my friend left it on an airplane, in the pocket of his front seat.  So be careful.  I had other instances where I almost lost it myself.</p>
					<p class="section-p blog-post-p">I had spent lots of time playing it.  Unlike the Ross, the electronic sensors are much smaller.  Therefore, you have to be more “accurate” to hit the sensors.  The Ross’ sensors are big and clunky (and may eventually stop working as already pointed out).  Another very useful feature of the Faegerstrom is that it reveals crossing noises very well.  In fact, they describe it on their features as “unforgiving at detecting crossing noise.”  And obviously as a piper, knowing when crossing noises are happening, is of the utmost importance if you want to get better.</p>
					<p class="section-p blog-post-p">I like the ease of programming the Faegerstrom, although I could see that being a nightmare for some people.  In order to do the programming you have to hold down some of the sensors before usually entering 2 more sensors in the back (near the bottom).  For the most part the main features I’d want to use were the metronome, instrument select, and mute.  Sometimes I would forget which sensors to hold to access the other features.  Because I have dabbled so much with programming synths, it wasn’t too bad to figure out on my own without the manual around.  However if you are less technically inclined or if you lost the manual that could be a problem.  If I forgot the feature I was trying to access, I would just try to figure it by trying a different sensor combination.  And if the chanter settings got really wonky (say the bagpipe was playing in the key of Z), I’d do a factory reset, which was not easy to enter because it would require touching all 11 sensors.  (In order to do this I would have to play a “Low G” and then use my bottom hand thumb to touch the extra 2 sensors, which then begins to feel like some weird yoga pose or the game Twister.)</p>
					<p class="section-p blog-post-p">The metronome was uninspiring.  In fact one of the things I hated about it was that there was only a single click sound, which means no differentiation between accent and unaccented.  That particularly becomes annoying when practicing compound time signatures (6/8, 9/8, etc.).  Also, the metronome doesn’t allow programming rhythms beyond simple, even clicks.  So you wouldn’t be able to program a long and short beat, which is commonly used in 6/8 march metronome rhythms.  Their metronome is very bare bones, considering that was one of the main things I wanted to pay extra for.  What I do like about is that it’s quick and easy to turn on.  You can also tap the BPM that you want and you can use the double sensors on the back of the chanter to slightly increase or decrease the bpm that it’s currently playing at.</p>
					<p class="section-p blog-post-p">As for the instrument selection, I found myself switching between the small pipes, which are famous for its mellow sound, and the highland pipes.  The highland pipes have more “notes” because they include “false” notes: C natural, F natural, as well as others, compared to the small pipes.  Don’t expect these false notes to have the same pitch on your actual bagpipes though (since that’s more tricky to set up on pipes).  There is also an extra instrument on my TechnoPipes, however it was my least favorite of the 3.  It had a very buzzy sound for the drones and the chanter was a little abrasive; I only used it when I was bored with the other 2 instruments.</p>
					<p class="section-p blog-post-p">Going back to the Faegerstrom’s wrath against crossing noises, one thing I find annoying about it is that sometimes the Faegerstrom is too unforgiving.  <span class="italic">Sounds like an excuse because I’m not working on my crossing noises?</span>  On particular movements, especially anything to do with the note “D”, the Faegerstrom can be too active in producing artifacts.  I partly believe this is because the Faegerstrom wants to show sound differences when playing non-typical movements, e.g., trills and hiharins (a piobaireachd movement that incorporates a false D before a birl).  It also get annoying when playing D grace notes up to a C from a low A, which is common in hornpipes.  So while it may have been well intended to prevent bad habits, it almost can feel unnatural at times, because it really highlights these differences due to the way it was chosen to be programmed.  In fact, I almost have to make a mental note to dismiss when I hear some of the artifacts when playing the “D”.  However that then becomes a problem when having to distinguish what to dismiss and what to correct.  That all being said, it's better than the Ross, which doesn't really show any subtle crossing noises and could certainly create bad habits.</p>
					<p class="section-p blog-post-p">As for the other features on the Faegerstrom TechnoPipes…  You can record yourself playing. I never really found this feature useful but I suppose it could be if you wanted to play harmonies to a melody that you had pre-recorded.  You can also change keys and raise or drop the frequency of the chanter.   You can also change the drone configuration to have a baritone drone (to play a 5th) like how some smallpipes do.  You can also alter the sensitivity of the sensors, but I never found that to be necessary.  </p>
					<p class="section-p blog-post-p">Although the sensors are significantly better on the Faegerstrom than the Ross, occasionally I would get “dry hands” and it would act up a little, but in those cases, rather than use soap, I would do like any barbarian would do, and give a quick lick of my fingers.  That usually does the trick!  And I’m sure the people in my park were horrified. &#128540;</p>
					<p class="section-p blog-post-p">I should also mention that the Faegerstrom has good battery life, at least compared to the Blair.  And it requires only a single AAA battery.</p>
					<p class="section-p blog-post-p">Lastly, I did once happen to plug the Faegerstrom’s MIDI cable (which they include) to one of my old analog synths, an Oberheim OB-8 (which had one of the first MIDI ports ever released for synths, back in the early-mid 80’s, so it was a bit primitive).  I noticed right away that there seemed to be a lot of extra notes, probably pertaining to how the extra, false notes (mentioned earlier) and crossing noise notes were pre-programmed to MIDI notes.  Unfortunately these extra notes seemed somewhat excessive on producing unwanted notes from my synth and it didn’t seem natural.  <span class="italic">But then again what is natural about connecting an electronic bagpipe with MIDI to an old synth?</span>  That all being said, I did not spend a lot of time with the MIDI of the Faegerstrom.  According to the manual, you can select the MIDI channel of the Faegerstrom.  One thing I do like about its MIDI connectivity over the Blair’s is that it doesn’t use USB for the MIDI.   In case you are interested, <a href="https://modwiggler.com/forum/viewtopic.php?t=229943">USB isn’t the best for MIDI</a> if you are obsessed with time accuracy. </p>
					<p class="section-p blog-post-p">The Faegerstrom was a very noticeable upgrade from the Ross.  I bought the Ross for about $169 on Ebay; <span class="italic">I see a newer model going for $315</span>.  I bought The Faegerstrom  from a Canadian website (to get a discount since CAD is lower) and that was about $330.  Although the Faegerstrom was about double the price (about the same for the newer model), it is significantly better.  If you will spend a lot of time practicing it, it is worth it.  Furthermore, if you get the basic version of the Faegerstrom TechnoChanter, you might be quite satisfied with its basic features since, as already pointed out, some of these features may not be worth getting.  And the newer generation TechnoChanter is retailing for about $250 on ebay as of this publishing, which has extra features..</p>
					<p class="section-p blog-post-p">So now…  for the Cadillac…  THE Blair digital chanter.  The first question we must ask ourselves…  Is it worth it?  The Blair chanter is retailing for about $637—on the cheaper end—of bagpipe dealers.  In fact that is almost double the price of the Faegerstrom, about 4x what I paid for the Ross!  Does it live up?  You could literally buy a new set of bagpipes almost for this price or even a nice set of use vintage pipes.</p>
					<p class="section-p blog-post-p bold">Is it @#$%^& WORTH IT?</p>
					<p class="section-p blog-post-p">Thankfully I got to borrow the chanter from a friend for about a month so I could “try before I buy” should I decide to make the switch.  In fact, I swapped the Faegerstrom with him.</p>
					<p class="section-p blog-post-p">After spending about 5 minutes trying to figure out how to turn it on, my first impression when I played it was AHHHHHHH!  Not sure why that was.  Perhaps it was the very realistic sound of the pipes, which is very inspiring to play, as opposed to the very “electronic” sound of the Faegerstrom and the Ross.  Perhaps it was the sparkle of the reverb.  Immediately I loved the sound.</p>
					<p class="section-p blog-post-p">Upon further playing it I asked myself again the question.  Perhaps it was all just in my head and I was simply seduced by the reverb…  (Good reverb is always seductive).</p>
					<p class="section-p blog-post-p">I did notice quickly something that made the Blair better than the Faegerstrom: the grace noting (permit me to use that as a word) had a much more realistic sound and response.  If you play a nice, crisp grace note on the Blair it actually sounded like how it would on a highland bagpipe, as opposed to the stale sounding Faegerstrom.  </p>
					<p class="section-p blog-post-p">Like the Faegerstrom I was not a big fan of the metronome.  However, there were immediate significant improvements over the Faegerstrom because it had 2 separate clicks: accented and unaccented.  Furthermore you could put in exactly the BPM you wanted to play at.  Also, you could decide where the accent beat goes (to play in different time signatures), which is a huge plus over the Faegerstrom.  What I didn’t like about the metronome was that the accented click didn’t feel right for some reason.  My friend also agrees with me about this, so it isn’t just me.  Although I am being fussy about the metronome; it still is a big improvement.  After all, a metronome feature of an electronic bagpipe can be an important and crucial benefit.  The Blair is still a big step up in that feature.</p>
					<p class="section-p blog-post-p">As for its infamous sensors: unlike the Ross and Faegerstrom (and the Deger I believe), the Blair uses light sensors.  Therefore in order for the note to be activated the hole of the chanter (yes, it has holes, unlike other electronic bagpipes) has to be completely covered (at least theoretically) in order for the note to play.  Why does this matter?  Because unlike a bagpipe, if electronic sensors are partially touched, it will activate the note.  In a bagpipe the hole needs to be fully closed (to prevent air leakage) to produce a proper note change.  As for the Ross and Faegerstrom, the slightest touch could trigger a full note change.  So what is the drawback of the Blair’s light sensors?  Well, for giggles, you could actually trigger a note by having your finger block the light from entering the hole but without covering the hole completely.  This is unlikely but I was able to pull it off.  Furthermore, in certain lighting conditions, I’ve seen the sensors go wonky.  This had occurred at the park when the sun was about to go down (the sun was going down around 5 P.M. since it’s late Fall and is thus darker that time of year).  This also happened in my room with low lighting.  What was the culprit?  The “G” hole.  Because the "G" hole is in the back, your body will cover much light from entering the hole.  After making some adjustments in the park with the “High G” sensor, it became fine.  That all being said, if you play around with the Blair’s sensors you can get a great feel.  In fact, Andrew Douglas of Piper’s Dojo has provided a spreadsheet of what he thinks are the best settings for the <a href="https://docs.google.com/spreadsheets/d/14cAkMGiaoS4E3IKwwoZHaPJoo5mxgBCeCBOEHvAZ7-I/edit#gid=0">Blair digital bagpipes' finger sensors.</a>  Each hole also can actually be individually adjusted unlike the Faegerstrom, which does adjustments universally for all the holes.  </p>
					<p class="section-p blog-post-p">As mentioned before, the Blair sounds great and so does its other feature instruments.  I also love the fact that there are practice chanter options to select.  This comes in handy if you want to practice along to a practice chanter recording from your band.</p>
					<p class="section-p blog-post-p">You can tune the instruments' exact frequency number.  Also very useful.</p>
					<img class="blog-post-image" src="../img/blair-digital-chanter.jpeg" alt="Blair Digital Chanter Menu Screen">
					<p class="section-p blog-post-p">At first I wasn’t a big fan of the menu selector wheel/button, which actually is a 2-in-1 component.  When navigating through the extensive layout of the menu, it can be a little annoying to alternate between using the wheel scroll and the button to click.  If you are going through the extensive menu, it can be a bit exhausting if you have to travel far to a different part of the menu.  That all said, from an engineering perspective, due to the richness of features in the Blair, the menu screen of the Blair is a practical requirement. I think I would have just preferred had they separated the wheel from the button into separate components.  They could have perhaps used 4 arrow buttons instead.  And it did make me appreciate the sipmlicity of the Faegerstrom's way of accessing its features.</p>
					<p class="section-p blog-post-p">Speaking of the menu, which is a major feature of the Blair, it is probably the main culrpit as to why the battery doesn’t last long.  Unlike the Faegerstrom which gets a reasonable amount of playtime before the battery goes, the Blair’s internal battery will constantly need to be recharged.  And unlike the Faegerstrom, which can use backup, disposable or reusable batteries, the Blair will have to be recharged every time with a USB.  Therefore there cannot be continuous practice if it dies (which usually happens after only a few hours).  I also wish the menu would show how much battery is left before being fully charged.  Being that the battery is internal, it is hoped that the battery life lasts.  (If the battery is overcharged for long hours, which happens to cell phones and laptops, there is a tendency for the battery to lose its life).  This is yet to be determined, of course.  If a battery would need to be replaced that would require you to send it in or replace it yourself (assuming you know how to solder electric components).  Of course, that all being said, using an external battery like the Blair may have been a worse option since it may have required either a lot of batteries or constant replacing.  The choices poor engineers must make!</p>
					<p class="section-p blog-post-p">Another great feature is that you can download other instruments. You can also upgrade the software from their website.  That is reassuring since it shows Blair is staying on top of its development.  The last thing you want to do is shell out over $600 and then they discontinue support.</p>
					<p class="section-p blog-post-p">So what happened in the end?  Well, even though I said I was going to borrow the Blair for only a week, to see if it was worth it, it actually became a month.  When I got the Faegerstrom back initially it didn’t feel so bad.  I was also concerned that my crossing noises would notoriously be revealed, but thankfully that wasn’t the case.  </p>
					<p class="section-p blog-post-p">And then after a while I just found myself practicing less.  I found the Faegerstrom to be somewhat uninspiring.  Where before I could pick up the Blair and use it for hours (which I had done before with the Faegerstrom), I just didn’t want to do so anymore with the Faegerstrom.  I also found my birls becoming an issue because of the nature of its sensors.  So… I sold the Faegerstrom and placed an order for the Blair.  I know it isn’t cheap but I believe the Blair would be that much of an asset.  Time is money and if the Blair is going to help me get that much more practice then so be it.  It’s a great piece.  (That all being said, the Faegerstrom still is a great price option and isn’t bad at all—until you get lulled by the Blair).</p>
					<p class="section-p blog-post-p">Now if only I put in all those hours to actually playing on an actual set of pipes…  The best way to practice is on the actual bagpipes, but supplementing your practice time is also positive.</p>
					<p class="section-p blog-post-p"><span class="bold">SO WHATEVER HAPPENED TO THE ROSS?</span>  Well, after reading their manual and contacting customer support, to see if there was anything I could do get rid of the crazy note changes besides wiping the sensors with a dry cloth and replacing the battery, I ended up wiping the sensors down with de-oxit contact spray.  Shortly afterwards the “F” note sensor fell out.  This not only revealed that it needed to be glued back (obviously), but the reason why it was going crazy to begin with was because there was a bad solder joint.  Each sensor is soldered to a cable as I had learned when I started to tear the thing open.  Although I figured out what the problem was and had soldered the cable back other wires started to come out.  I admit I am not good at electronic repair but I was not happy with the Ross.  I’ll eventually get around to fixing it.</p>
					<p class="section-p blog-post-p">Although I noticed an improvement in the sensors after spraying, there’s definitely a slight delay in the response that the Faegerstrom and the Blair didn’t have.  This may not be noticeable to some, but I could notice it and didn’t like it.  It would definitely be an issue for playing fast or complicated tunes.  And that ugly, big box…</p>
					<img class="blog-post-image" src="../img/ross-bagpipe-chanter.jpeg" alt="Ross Digital Chanter Speaker Box">
					<p class="section-p blog-post-p">Happy piping.</p>

          <p class="section-p blog-post-p section-border-space"><span class="italic">Published: November 20th, 2021</span></p>
					
					<div class="section-border"></div>
					<p class="section-p questions">Have any questions? Shoot me an <a href="mailto: nycbagpipes@gmail.com">email</a>.</p>
					
			</section>
							
			<?php require "../components/footer.php";?>
		</div>
		<script src="../script.js"></script>
	</body>
</html>